### PR TITLE
Implement ADO pipeline build instead of TeamCity

### PR DESCRIPTION
**Pull request by peterix**
Same as the other repos, just public.

[The ADO pipelines have disabled building from forks.](https://dev.azure.com/dev-mc/Java%20Minecraft/_build?_a=allDefinitions&path=%5CBrigadier%5C)

### CODE REVIEW

**Comment by peterix** [comment]
TODO: remove `continuous-integration/teamcity` as required, add `Brigadier - Build `.

**Review by parberge — APPROVED** [review]
Looks good to me.

**Review by BHellstream — APPROVED** [review]
Lgtm

**Comment by Pokechu22** [comment]
I'm unable to load https://dev.azure.com/dev-mc/Java%20Minecraft/_build?_a=allDefinitions&path=%5CBrigadier%5C myself (so if that URL is supposed to be public, it doesn't seem to have been configured correctly).

**Comment by BHellstream** [comment]
> I'm unable to load https://dev.azure.com/dev-mc/Java%20Minecraft/_build?_a=allDefinitions&path=%5CBrigadier%5C myself (so if that URL is supposed to be public, it doesn't seem to have been configured correctly).

That is not supposed to be public, so that's fine for now, thanks for the input.

**Comment by peterix** [comment]
Well, CLA is signed, but the bot is not responding or acting on it ... Not sure what happened there.

**Comment by peterix** [comment]
And CLA assistant woke up. Maybe it's just a cron job that doesn't run that often and I'm impatient :)

**Pull request merged**
