### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TheIntelloBox**

### CODE REVIEW

**Comment by TheIntelloBox** [comment]
Done ! :D

**Comment by jamierocks** [comment]
Since you're on it - s/`new CommandDispatcher(`/`new Command dispatcher<>(`

**Comment by Earthcomputer** [comment]
And since we're being really picky: `When a command is actually ran` -> `When a command is actually run`
:P

**Comment by Dinnerbone** [comment]
And all of those in the same commit/PR, please? :D

**Comment by TheIntelloBox** [comment]
@jamierocks What must I change ?

**Comment by Earthcomputer** [comment]
This line
```java
CommandDispatcher<CommandSourceStack> dispatcher = new CommandDispatcher();
```
Should read
```java
CommandDispatcher<CommandSourceStack> dispatcher = new CommandDispatcher<>();
```

**Comment by TheIntelloBox** [comment]
No problem sir ! :D

**Pull request merged**
