### PR TITLE
Make fork and star buttons clickable

### PR DESCRIPTION
**Pull request by theel0ja**

### CODE REVIEW

**Comment by r00ster91** [comment]
Why not making the Stars button work too? It should go to https://github.com/Mojang/brigadier/stargazers.

**Comment by JarvisCraft** [comment]
@theel0ja sent *Stars* clickable as PR to your `patch-1` branch

**Comment by theel0ja** [comment]
@JarvisCraft merged.

https://github.com/theel0ja/brigadier/pull/1

**Comment by r00ster91** [comment]
The PR title should be changed.

**Pull request merged**
