### PR TITLE
Add shields (from shields.io) to README.md

### PR DESCRIPTION
**Pull request by JarvisCraft**
This simple adds some *shields* to `README.md` so that it looks more user-friendly

### CODE REVIEW

**Comment by FakeZane** [comment]
Might as well add this... 
[GitHub release](https://github.com/Mojang/brigadier/releases)

**Comment by MiniDigger** [comment]
I think I would prefer it to have the license badge on the same line as the heading, the badges on the bottom of the page seem kinda useless

**Comment by JarvisCraft** [comment]
> I think I would prefer it to have the license badge on the same line as the heading, the badges on the bottom of the page seem kinda useless

@MiniDigger, the bottom ones are social-icons. I've put them to make the end of README more *beautifully-looking* as the text simply ends with some usage-theory which (I think) may be *diluted* with some icons:
GitHub forks GitHub stars

**Comment by JarvisCraft** [comment]
> I think I would prefer it to have the license badge on the same line as the heading, the badges on the bottom of the page seem kinda useless

@MiniDigger I've also tried putting license shield on the same line as the title but it looked a bit of unpleasantly shrinked there

**Comment by JarvisCraft** [comment]
@Dinnerbone what do you like the most?
___
This
***№0***
# Brigadier
GitHub release GitHub
___
Or this
***№1***
# Brigadier GitHub release GitHub
___
___

The ones with 1 inlined and one outlined seem not very good
***№2***
# Brigadier GitHub release
GitHub
___
... and are better when version (being longer then license) is in the second line
***№3***
# Brigadier GitHub
GitHub release
___
___
This may also be a variant but I feel like two rows is too much for it
***№4***
# Brigadier
GitHub release
GitHub
___

**Comment by kashike** [comment]
Number one gets my vote.

**Comment by Dinnerbone** [comment]
Number 1 is definitely coolest.

**Pull request merged**
