### PR TITLE
Custom result type

### PR DESCRIPTION
**Pull request by ramidzkh**
Allows for a custom result type, other than just an integer

### CODE REVIEW

**Comment by jearmstrong21** [comment]
I really like this - any word on whether this is a feature Mojang would want to use?

**Comment by NeunEinser** [comment]
> I really like this - any word on whether this is a feature Mojang would want to use?

Mojang has not worked on PRs for like 1.5 years now, so nope

**Comment by liach** [comment]
This is a great feature and it appears to work great. However this is not backward compatible and will need a major version bump most likely, but is worth it.

**Comment by hYdos** [comment]
hmmm... wonder how we can get someone to review this

**Review by haykam821 — APPROVED** [review]

**Review by YTG1234 — APPROVED** [review]

**Review by Devan-Kerman — APPROVED** [review]

**Comment by ramidzkh** [comment]
Looks like generic hell anyway

**Pull request closed without merging**
